version: 2.1

jobs:

  install_aws_cli:
    docker:
      - image: amazonlinux:2
    steps:
      - run:
          name: Install AWS CLI
          command: |
            apk update
            apk add --no-cache aws-cli
            aws configure set aws_access_key_id $TF_VAR_access_key
            aws configure set aws_secret_access_key $TF_VAR_secret_key
            aws configure set default.region ap-south-1
      - persist_to_workspace:
          root: /workspace
          paths:
            - /root/.aws

  
  terraform_init:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /workspace
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Terraform Init
          command: |
            cd env/infra
            terraform init
             
              

  terraform_plan:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /workspace
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Terraform Plan
          command: |
            cd env/infra
            terraform plan

  terraform_apply_output:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /workspace
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Terraform Apply & Output
          command: |
            cd env/infra
            terraform destroy --auto-approve

# -var-file="${ENV}.tfvars" --auto-approve
workflows:
  version: 2
  Init-Apply-Output:
    jobs:
      - install_aws_cli
      - terraform_init:
          requires:
            - install_aws_cli
      - terraform_plan:
          requires:
            - terraform_init
      - terraform_apply_output:
          requires:
            - terraform_plan
          filters:
            branches:
              only: dev